config/routes.rb
Rails.application.routes.draw do
  root 'mountains#index'
  resources :mountains
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mountain.rb
class Mountain < ApplicationRecord
end

app/models/summit.rb
class Summit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController

  def index
    @mountains = Mountain.all
  end

  def new
    @mountain = Mountain.new
  end

  def create
    Mountain.create(mountain_params)
    redirect_to root_path
  end

  private

  def mountain_params
    params.require(:mountain).permit(:name, :elevation, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mountains_helper.rb
module MountainsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mountains</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
      <%= link_to 'Mountians', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to 'Add a Mountain', new_mountain_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/mountains/index.html.erb
<% @mountains.each do |mountain| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= mountain.name %></h1>
    <h2><%= mountain.elevation %></h2>
    <h3><%= mountain.description %></h3>
  </div>
<% end %>

app/views/mountains/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Add your favorite mountain</h1>
  <%= simple_form_for @mountain do |f| %>
    <%= f.input :name %>
    <%= f.input :elevation %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>